GET https://phonebook-backend-misty-shape-1020.fly.dev/api/persons

###
DELETE https://phonebook-backend-misty-shape-1020.fly.dev/api/persons/5

###
POST https://phonebook-backend-misty-shape-1020.fly.dev/api/persons
Content-Type: application/json

{
"id": 5, "name": "Hannu Rautiainen", "number": "+35812345678"
}
###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
"name": "Ye", "number": "+35812345678"
}